services:

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - backend-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.3
    container_name: keycloak
    command: start-dev
    restart: always
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: ${KEYCLOAK_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HTTP_PORT: 9090
      KC_HOSTNAME: keycloak
      KC_HOSTNAME_PORT: 9090
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HTTP_ENABLED: "true"
    ports:
      - "9090:9090"
    depends_on:
      - postgres
    networks:
      - backend-network

  saga-orchestrator:
    build: ./saga-orchestrator
    container_name: saga-orchestrator
    environment:
      DB_HOST: postgres
      SAGA_DB: ${SAGA_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - postgres
    networks:
      - backend-network

  order-service:
    build: ./order-service
    container_name: order-service
    environment:
      DB_HOST: postgres
      ORDER_DB: ${ORDER_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - postgres
    networks:
      - backend-network

  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    environment:
      DB_HOST: postgres
      INVENTORY_DB: ${INVENTORY_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - postgres
    networks:
      - backend-network

  dispatch-service:
    build: ./dispatch-service
    container_name: dispatch-service
    environment:
      DB_HOST: postgres
      DISPATCH_DB: ${DISPATCH_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - postgres
    networks:
      - backend-network

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    environment:
      KEYCLOAK_ISSUER_URI: http://keycloak:9090/realms/order-realms
    ports:
      - "8080:8080"
    depends_on:
      - keycloak
      - order-service
      - inventory-service
      - dispatch-service
      - saga-orchestrator
    networks:
      - backend-network

networks:
  backend-network:

volumes:
  postgres_data: