spring.application.name=api-gateway

spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://keycloak:9090/realms/order-realms}

services.order-service.url=${ORDER_SERVICE_URL:http://order-service:8082}
services.inventory-service.url=${INVENTORY_SERVICE_URL:http://inventory-service:8083}
services.saga-orchestrator.url=${SAGA_ORCHESTRATOR_URL:http://saga-orchestrator:8081}

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs