INSERT INTO products (
    id,
    name,
    description,
    price,
    active,
    created_at,
    updated_at
)
VALUES
    (gen_random_uuid(), 'Laptop Lenovo IdeaPad', 'Laptop Lenovo IdeaPad 15 pulgadas', 2899.90, true, NOW(), NOW()),
    (gen_random_uuid(), 'Mouse Logitech M185', 'Mouse inalámbrico Logitech', 59.90, true, NOW(), NOW()),
    (gen_random_uuid(), 'Teclado Mecánico Redragon', 'Teclado mecánico RGB', 199.90, true, NOW(), NOW()),
    (gen_random_uuid(), 'Monitor Samsung 24"', 'Monitor Full HD de 24 pulgadas', 699.00, true, NOW(), NOW()),
    (gen_random_uuid(), 'Disco SSD Kingston 1TB', 'Unidad SSD SATA de 1TB', 329.50, true, NOW(), NOW()),
    (gen_random_uuid(), 'Memoria RAM 16GB', 'DDR4 3200MHz', 249.90, true, NOW(), NOW()),
    (gen_random_uuid(), 'Audífonos JBL Tune', 'Audífonos inalámbricos Bluetooth', 189.90, true, NOW(), NOW()),
    (gen_random_uuid(), 'Webcam Logitech C920', 'Cámara web Full HD', 349.90, true, NOW(), NOW()),
    (gen_random_uuid(), 'Impresora Epson L3250', 'Impresora multifuncional WiFi', 799.90, true, NOW(), NOW()),
    (gen_random_uuid(), 'Silla Gamer Cougar', 'Silla ergonómica gamer', 1199.00, true, NOW(), NOW()),
    (gen_random_uuid(), 'Tablet Samsung A9', 'Tablet Android de 10 pulgadas', 899.00, true, NOW(), NOW()),
    (gen_random_uuid(), 'Smartphone Xiaomi Redmi Note 14', 'Celular 256GB', 1499.00, true, NOW(), NOW()),
    (gen_random_uuid(), 'Power Bank Xiaomi', 'Batería portátil 20000mAh', 129.90, true, NOW(), NOW()),
    (gen_random_uuid(), 'Cable USB-C', 'Cable de carga rápida 1 metro', 29.90, true, NOW(), NOW()),
    (gen_random_uuid(), 'Router TP-Link AX1800', 'Router WiFi 6', 399.90, true, NOW(), NOW()),
    (gen_random_uuid(), 'Parlante JBL Flip 6', 'Parlante Bluetooth portátil', 549.90, true, NOW(), NOW()),
    (gen_random_uuid(), 'Smartwatch Huawei GT4', 'Reloj inteligente', 899.90, true, NOW(), NOW()),
    (gen_random_uuid(), 'Cargador USB-C 65W', 'Cargador de carga rápida', 119.90, true, NOW(), NOW()),
    (gen_random_uuid(), 'Disco Externo Seagate 2TB', 'Disco duro portátil USB 3.0', 449.90, true, NOW(), NOW()),
    (gen_random_uuid(), 'Micrófono HyperX SoloCast', 'Micrófono USB para streaming', 279.90, true, NOW(), NOW());